### ISSUE TITLE
Java 11 error

### ISSUE THREAD

**Issue by hafarooki** [Dahaka934/JHocon#1]
Fails to create the JHocon object on Java 11

```
[07:42:39 ERROR]: Could not load 'plugins/SLCore.jar' in folder 'plugins'                                                      
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalAccessError: class com.google.gson.internal.bind.ReflectiveTypeAdapterFactoryEx$1 cannot access its abstract superclass com.google.gson.internal.bind.Refl
ectiveTypeAdapterFactory$BoundField (com.google.gson.internal.bind.ReflectiveTypeAdapterFactoryEx$1 is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @60c30caf; com.google.gson.internal.bind.
ReflectiveTypeAdapterFactory$BoundField is in unnamed module of loader 'app')                                              
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1589]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1589]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[patched_1.12.2.jar:git-Paper-1589]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[patched_1.12.2.jar:git-Paper-1589]  
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1589] 
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1589] 
        at java.lang.Thread.run(Thread.java:834) [?:?]                                                                     
Caused by: java.lang.IllegalAccessError: class com.google.gson.internal.bind.ReflectiveTypeAdapterFactoryEx$1 cannot access its abstract superclass com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$BoundF
ield (com.google.gson.internal.bind.ReflectiveTypeAdapterFactoryEx$1 is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @60c30caf; com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Bo
undField is in unnamed module of loader 'app')                               
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]                                                            
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]                                                     
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]                                    
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[patched_1.12.2.jar:git-Paper-1589]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1589]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]       
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]           
        at com.github.dahaka934.jhocon.JHoconBuilder.getReflectFactory(JHoconBuilder.java:107) ~[?:?]                          
        at com.github.dahaka934.jhocon.JHoconBuilder.registerFieldHandler(JHoconBuilder.java:48) ~[?:?]                        
        at com.github.dahaka934.jhocon.JHoconBuilder.withComments(JHoconBuilder.java:88) ~[?:?]                              
        at net.starlegacy.slcore.framework.SLPlugin.<init>(SLPlugin.kt:174) ~[?:?]                                          
        at net.starlegacy.slcore.SLCore.<init>(SLCore.kt:17) ~[?:?]                                                        
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]                                              
        at java.lang.Class.newInstance(Class.java:584) ~[?:?]                                                                
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:94) ~[patched_1.12.2.jar:git-Paper-1589]  
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1589]
        ... 6 more
```

**Comment by Dahaka934** [comment]
Strange bug.
I tried to fix it, but not sure that it works.
The problem is not in Java 11. Because I tried it and everything worked fine for me. Perhaps this is problem with bukkit class loader.

**Comment by MicleBrick** [comment]
Okay, thanks for trying, I'll see if it worked, and if not I'll see if I can reproduce it in a standalone application.

**Comment by hohserg1** [comment]
You are using JHoconConfig for bukkit? Is it designed to run with Java 11?
https://help.mojang.com/customer/en/portal/articles/325948-minecraft-java-edition-system-requirements

**Comment by MicleBrick** [comment]
[Paper 1.12.2](https://papermc.io) runs fine on Java 11.

**Comment by hohserg1** [comment]
May be. But documentation of Paper advises useing java 8
https://paper.readthedocs.io/en/stable/about/faq.html#what-do-i-need-to-run-it

**Comment by aikar** [comment]
@MicleBrick :taco:

**Comment by Cryptite** [comment]
> May be. But documentation of Paper advises using java 8
> https://paper.readthedocs.io/en/stable/about/faq.html#what-do-i-need-to-run-it

Id advises using **at least** 8. Higher versions reportedly work just fine.

**Comment by MicleBrick** [comment]
At any rate, the fix worked, tyvm :heart:

**Comment by Dahaka934** [comment]
Oh, I have a one idea. I will try it now.

**Comment by MicleBrick** [comment]
I think this issue is a mix of java 11 and the bukkit class loader, since they're in different modules, Java doesn't let it access the package private method regardless of the fact that they're in the same package.

**Comment by MicleBrick** [comment]
I thought I could replace the same package stuff with reflection, but that doesn't work because you can't override a package private method...

**Comment by Dahaka934** [comment]
I can override package private method, but in runtime make accessable this method.
```java
static {
    try {
        Method m = JsonReaderStub.class.getDeclaredMethod("doPeek");
        ReflectionAccessor.getInstance().makeAccessible(m);
    } catch (NoSuchMethodException e) {
        e.printStackTrace();
    }
}
```
But I do not understand how writing is worked. Most likely you are trying to write an object of your class. Therefore, should be called ReflectiveTypeAdapterFactoryEx#createBoundField. But there is also creating object of the package privite class. How it works? Could you debug this moment?

https://github.com/Dahaka934/JHocon/blob/471e4a5cd3b1e4ad1621e05bdd1ec3922201ab0c/src/main/java/com/google/gson/internal/bind/ReflectiveTypeAdapterFactoryEx.java#L130

**Comment by Dahaka934** [comment]
Also, you can try last commit.

**Comment by MicleBrick** [comment]
Didn't work, sadly:
```
java.lang.IllegalAccessError: class com.google.gson.stream.JsonReaderStub tried to access field com.google.gson.stream.JsonReader.peeked (com.google.gson.stream.JsonReaderStub is in unnamed module of loader org.b$
        at com.google.gson.stream.JsonReaderStub.setPeeked(JsonReaderStub.java:38) ~[?:?]
        at com.github.dahaka934.jhocon.reader.JHoconReader.peek(JHoconReader.java:45) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:883) ~[minecraft_server.jar:git-Paper-1589]
        at com.github.dahaka934.jhocon.JHocon.fromHocon(JHocon.java:190) ~[?:?]
        at com.github.dahaka934.jhocon.JHocon.fromHocon(JHocon.java:229) ~[?:?]
        at com.github.dahaka934.jhocon.JHocon.fromHocon(JHocon.java:245) ~[?:?]
        at net.starlegacy.StarLegacy.onEnable(StarLegacy.kt:418) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[minecraft_server.jar:git-Paper-1589]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[minecraft_server.jar:git-Paper-1589]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[minecraft_server.jar:git-Paper-1589]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[minecraft_server.jar:git-Paper-1589]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[minecraft_server.jar:git-Paper-1589]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[minecraft_server.jar:git-Paper-1589]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[minecraft_server.jar:git-Paper-1589]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[minecraft_server.jar:git-Paper-1589]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[minecraft_server.jar:git-Paper-1589]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[minecraft_server.jar:git-Paper-1589]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
(using 72c23f3)

I'm not sure what exactly you mean about debug that moment

Would it be possible to use jhocon's annotations on top of the regular typesafe config stuff? Since that does work fine

**Comment by hafarooki** [comment]
It appears I was wrong about it working with serializing, since it just failed to do so :stuck_out_tongue: I'm not really sure how it worked before, but it was before I even tried just using the regular typesafe config method.

**Comment by Dahaka934** [comment]
Try a new commit :)

**Comment by hafarooki** [comment]
Still: `java.lang.IllegalAccessError: class com.google.gson.stream.JsonReaderStub tried to access field com.google.gson.stream.JsonReader.peeked (com.google.gson.stream.JsonReaderStub is in unnamed module of loader org.bu
kkit.plugin.java.PluginClassLoader @552428a1; com.google.gson.stream.JsonReader is in unnamed module of loader 'app')` which is a little strange since it's setting it to accessible

**Comment by Dahaka934** [comment]
Ohh.. I dont know yet how to fix it.
